/* ==========================================================================
   ENTITY DEFINITIONS — matches the REAL Supabase schema exactly, including
   each column's REAL Postgres data type (checked via information_schema,
   not guessed from the name — several columns that sound like dates/numbers
   are actually stored as plain text, e.g. DATATABLE.SALARY, all of
   VISAEXPNECE's amount columns, and most of DATATABLE's *DATE columns).

   Table/column name casing is case-sensitive here (quoted identifiers),
   e.g. "AGENT", "BIO DATA", "AgencyID" — do not rename without checking
   Supabase's Table Editor first.

   field types: text | number | date | textarea | select(FK)
   ========================================================================== */
window.ENTITIES = [
  // ---------------- CORE ----------------
  {
    key: "agent", table: "AGENT", pk: "COID", label: "Agents", icon: "fa-user-tie",
    group: "Core", displayField: "AGENTNAME", agencyField: "AGENCYID",
    fields: [
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "AGENTNAME", label: "Agentname", type: "text", required: true },
      { name: "AGENCY", label: "Agency", type: "text" },
      { name: "RESIDENT", label: "Resident", type: "text" },
      { name: "TEL", label: "TEL", type: "text" },
      { name: "MOB", label: "MOB", type: "text" },
      { name: "EMAIL", label: "Email", type: "text" },
      { name: "CHECK", label: "Check", type: "text" },
    ],
  },
  {
    key: "company", table: "COMPANY", pk: "AGENCYID", label: "Companies", icon: "fa-building",
    group: "Core", displayField: "AGENCYNAME", agencyField: "AGENCYID",
    fields: [
      { name: "AGENCYNAME", label: "Agencyname", type: "text", required: true },
      { name: "NAMEOFOWNER", label: "Nameofowner", type: "text" },
      { name: "OWNERTYPE", label: "Ownertype", type: "text" },
      { name: "OFFICEADDRESS", label: "Officeaddress", type: "textarea" },
      { name: "TELEPHONE", label: "Telephone", type: "text" },
      { name: "MOBILENUMBER", label: "Mobilenumber", type: "text" },
      { name: "LICENCENUMBER", label: "Licencenumber", type: "text" },
      { name: "LICENECEVALIDUPTO", label: "Licenecevalidupto", type: "number" },
      { name: "LICENCE", label: "Licence", type: "text" },
      { name: "LOGO", label: "Logo", type: "text" },
      { name: "NAMEOFPARTNER", label: "Nameofpartner", type: "text" },
    ],
  },
  {
    key: "category", table: "CATEGORY", pk: "CATEGORYID", label: "Categories", icon: "fa-layer-group",
    group: "Core", displayField: "CATEGORY", search: ["CATEGORY", "EMPID"], agencyField: "AgencyID",
    fields: [
      { name: "SALARY", label: "Salary", type: "text" },
      { name: "CATEGORYARBIC", label: "Categoryarbic", type: "text" },
      { name: "AgencyID", label: "Agencyid", type: "select", ref: "company" },
      { name: "CATEGORY", label: "Category", type: "text", required: true },
      { name: "REQTRADE", label: "Reqtrade", type: "text" },
      { name: "QUANTITY", label: "Quantity", type: "number" },
      { name: "EXPENCE", label: "Expence", type: "number" },
      { name: "SELECT", label: "Select", type: "staticselect", options: ["True", "False"] },
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
    ],
  },
  {
    key: "employer", table: "EMPLOYER", pk: "EMPID", label: "Employers", icon: "fa-briefcase",
    group: "Core", displayField: "NAMEOFEMPLOYER", search: ["NAMEOFEMPLOYER", "VISANO"], agencyField: "AGENCYID",
    fields: [
      { name: "NAMEOFEMPLOYER", label: "Nameofemployer", type: "text", required: true },
      { name: "ADDRESSOFEMPLOYER", label: "Addressofemployer", type: "textarea" },
      { name: "VISANO", label: "Visano", type: "text" },
      { name: "IDNO", label: "Idno", type: "text" },
      { name: "DEMAND", label: "Demand", type: "number" },
      { name: "PERMISSIONNO", label: "Permissionno", type: "text" },
      { name: "DATED", label: "Dated", type: "date" },
      { name: "ATTACHMENT", label: "Attachment", type: "text" },
      { name: "FILENO", label: "Fileno", type: "text" },
      { name: "PERMISSIONEXP", label: "Permissionexp", type: "text" },
      { name: "ACTIVE", label: "Active", type: "staticselect", options: ["True", "False"] },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "ENTRYDATE", label: "Entrydate", type: "text" },
      { name: "EMBASSYIN", label: "Embassyin", type: "staticselect", options: ["Karachi", "Islamabad"] },
      { name: "VISADATE", label: "Visadate", type: "text" },
      { name: "CITY", label: "City", type: "text" },
      { name: "VISATYPE", label: "Visatype", type: "text" },
      { name: "ARBICCOMPANY", label: "Arbiccompany", type: "text" },
      { name: "C/O", label: "C/O", type: "text" },
    ],
  },
  {
    key: "datatable", table: "DATATABLE", pk: "DID", label: "DATATABLE", icon: "fa-id-card",
    group: "Core", displayField: "NAME", search: ["NAME", "PASSPORTNO"], agencyField: "AGENCYID",
    fields: [
      { name: "COID", label: "Coid", type: "select", ref: "agent" },
      { name: "NAMEOFEMPLOYER", label: "Nameofemployer", type: "text" },
      { name: "NAME", label: "Name", type: "text", required: true },
      { name: "FATHERSNAME", label: "Fathersname", type: "text" },
      { name: "PASSPORTNO", label: "Passportno", type: "text" },
      { name: "VISANO", label: "Visano", type: "text" },
      { name: "NAMEOFOWNER", label: "Nameofowner", type: "text" },
      { name: "NAMEOFEGENCY", label: "Nameofegency", type: "text" },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "CATEGORYID", label: "Categoryid", type: "select", ref: "category" },
      { name: "Enumber", label: "Enumber", type: "text" },
      { name: "CATEGORY", label: "Category", type: "text" },
      { name: "STATUS", label: "Status", type: "text" },
      { name: "VISASTAMPED", label: "Visastamped", type: "text" },
      { name: "TRAVELDATE", label: "Traveldate", type: "text" },
      { name: "Embassyin", label: "Embassyin", type: "text" },
      { name: "LICENSE NO", label: "License NO", type: "text" },
      { name: "NIC", label: "NIC", type: "text" },
      { name: "ADDRESS", label: "Address", type: "textarea" },
      { name: "DISTRICT", label: "District", type: "text" },
      { name: "DATEOFBIRTH", label: "Dateofbirth", type: "text" },
      { name: "PLACEOFBIRTH", label: "Placeofbirth", type: "text" },
      { name: "DATEOFISSUE", label: "Dateofissue", type: "text" },
      { name: "DATEOFEXPIRY", label: "Dateofexpiry", type: "text" },
      { name: "PLACEOFISSUE", label: "Placeofissue", type: "text" },
      { name: "COUNTRY", label: "Country", type: "text" },
      { name: "CONTRACT", label: "Contract", type: "text" },
      { name: "SALARY", label: "Salary", type: "text" },
      { name: "PERMISSIONNO", label: "Permissionno", type: "text" },
      { name: "DATED", label: "Dated", type: "text" },
      { name: "ADDRESSOFEMPLOYER", label: "Addressofemployer", type: "textarea" },
      { name: "NAMEOFINSURANCE", label: "Nameofinsurance", type: "text" },
      { name: "AGEOFINSURANCE", label: "Ageofinsurance", type: "text" },
      { name: "RELATIONOFINSURANCE", label: "Relationofinsurance", type: "text" },
      { name: "ADDRESSOFINSURANCE", label: "Addressofinsurance", type: "textarea" },
      { name: "NICOFINSURANCE", label: "Nicofinsurance", type: "text" },
      { name: "Qualification", label: "Qualification", type: "text" },
      { name: "DATE", label: "Date", type: "text" },
      { name: "MEDICALNAME", label: "Medicalname", type: "text" },
      { name: "AUTHORIZATION", label: "Authorization", type: "text" },
      { name: "GMCA", label: "GMCA", type: "text" },
      { name: "MEDICALDATE", label: "Medicaldate", type: "text" },
      { name: "CITY", label: "City", type: "text" },
      { name: "IDNO", label: "Idno", type: "text" },
      { name: "VISATYPE", label: "Visatype", type: "text" },
      { name: "VISADATE", label: "Visadate", type: "text" },
      { name: "ARBICNAME", label: "Arbicname", type: "text" },
      { name: "ARBICFATHERNAME", label: "Arbicfathername", type: "text" },
      { name: "ARBICCOMPANY", label: "Arbiccompany", type: "text" },
      { name: "ARBICTRADE", label: "Arbictrade", type: "text" },
      { name: "PURPOSE", label: "Purpose", type: "text" },
      { name: "TRAVELBY", label: "Travelby", type: "text" },
      { name: "FSANo", label: "FSANo", type: "text" },
      { name: "FSADate", label: "FSADate", type: "text" },
      { name: "DESTINATION", label: "Destination", type: "text" },
      { name: "FLIGHT", label: "Flight", type: "text" },
      { name: "Ticket No", label: "Ticket No", type: "text" },
      { name: "MERITALSTATUS", label: "Meritalstatus", type: "text" },
      { name: "SECT", label: "Sect", type: "text" },
      { name: "SEX", label: "Sex", type: "text" },
      { name: "RELIGION", label: "Religion", type: "text" },
      { name: "DEMAND", label: "Demand", type: "number" },
      { name: "SUBMIT", label: "Submit", type: "text" },
      { name: "ENDORSED", label: "Endorsed", type: "text" },
      { name: "BALANCE", label: "Balance", type: "text" },
      { name: "REQTRADE", label: "Reqtrade", type: "text" },
      { name: "REMARKS", label: "Remarks", type: "textarea" },
      { name: "E Barcode", label: "E Barcode", type: "text" },
      { name: "V Barcode", label: "V Barcode", type: "text" },
      { name: "Select", label: "Select", type: "text" },
      { name: "Photo", label: "Photo", type: "number" },
      { name: "Open", label: "Open", type: "text" },
      { name: "FileNo", label: "FileNo", type: "text" },
      { name: "LICNO", label: "Licno", type: "text" },
      { name: "QUANTITY", label: "Quantity", type: "number" },
      { name: "EXP", label: "Exp", type: "number" },
      { name: "EAMOUNT", label: "Eamount", type: "text" },
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
      { name: "STICKERNO", label: "Stickerno", type: "text" },
      { name: "NICISSUEDATE", label: "Nicissuedate", type: "text" },
    ],
  },
  {
    key: "bio_data", table: "BIO DATA", pk: "ID", label: "Candidate Bio Data", icon: "fa-address-card",
    group: "Core", displayField: "NAME", search: ["NAME", "TRADE"],
    fields: [
      { name: "SERIALNO", label: "Serialno", type: "number" },
      { name: "NAME", label: "Name", type: "text", required: true },
      { name: "FATHER NAME", label: "Father Name", type: "text" },
      { name: "COMPANY", label: "Company", type: "text" },
      { name: "TRADE", label: "Trade", type: "text" },
      { name: "AGENT", label: "Agent", type: "text" },
      { name: "WHATSAPP", label: "Whatsapp", type: "text" },
      { name: "MOBILE NO", label: "Mobile NO", type: "text" },
      { name: "REMARKS", label: "Remarks", type: "textarea" },
      { name: "DATE", label: "Date", type: "date" },
      { name: "photo", label: "Photo", type: "number" },
      { name: "STATUS", label: "Status", type: "text" },
      { name: "ACTIVE / NON ACTIVE", label: "Active / NON Active", type: "text" },
      { name: "NIC", label: "NIC", type: "text" },
      { name: "PASSPORT NO", label: "Passport NO", type: "text" },
      { name: "EXPECTED SALARY", label: "Expected Salary", type: "number" },
      { name: "EXPRIENCE", label: "Exprience", type: "number" },
    ],
  },
  {
    key: "tblcompany", table: "tblCompany", pk: "CompanyID", label: "Companies (Legacy)", icon: "fa-building-columns",
    group: "Core", displayField: "CompanyName",
    fields: [
      { name: "CompanyName", label: "Companyname", type: "text", required: true },
      { name: "CompanyWebsite", label: "Companywebsite", type: "text" },
    ],
  },
  {
    key: "tbl_user", table: "tbl_User", pk: "lngUserID", label: "User Accounts", icon: "fa-user-lock",
    group: "Core", displayField: "strUserName",
    fields: [
      { name: "Permission", label: "Permission", type: "text" },
      { name: "strUserName", label: "Strusername", type: "text", required: true },
      { name: "strUserPassword", label: "Struserpassword", type: "text" },
    ],
  },
  // ---------------- FINANCE ----------------
  {
    key: "account", table: "ACCOUNT", pk: "ACCID", label: "Accounts", icon: "fa-vault",
    group: "Finance", displayField: "NAME", agencyField: "AGENCYID",
    fields: [
      { name: "NAME", label: "Name", type: "text", required: true },
      { name: "ACCOUNTNO", label: "Accountno", type: "text" },
      { name: "ACCOUNTTITLE", label: "Accounttitle", type: "text" },
      { name: "DETAILS", label: "Details", type: "textarea" },
      { name: "NUMBER", label: "Number", type: "text" },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "SELECT", label: "Select", type: "text" },
    ],
  },
  {
    key: "rec", table: "REC", pk: "RECID", label: "Receipts", icon: "fa-receipt",
    group: "Finance", displayField: "RECEIPTNO", agencyField: "AGENCYID",
    fields: [
      { name: "RECEIVEDATE", label: "Receivedate", type: "date" },
      { name: "AMOUNT", label: "Amount", type: "number", required: true },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "RECEIPTNO", label: "Receiptno", type: "text" },
      { name: "COID", label: "Coid", type: "select", ref: "agent" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
      { name: "TYPE", label: "Type", type: "text" },
    ],
  },
  {
    key: "pay", table: "PAY", pk: "PAYID", label: "Payments", icon: "fa-money-bill-wave",
    group: "Finance", displayField: "DESCRIPTION", agencyField: "AGENCYID",
    fields: [
      { name: "PAYDATE", label: "Paydate", type: "date" },
      { name: "PAYAMOUNT", label: "Payamount", type: "number", required: true },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
      { name: "PAYTYPE", label: "Paytype", type: "text" },
    ],
  },
  {
    key: "refund", table: "REFUND", pk: "REFUNDID", label: "Refunds", icon: "fa-rotate-left",
    group: "Finance", displayField: "DESCRIPTION", agencyField: "AGENCYID",
    fields: [
      { name: "REFUNDDATE", label: "Refunddate", type: "date" },
      { name: "REFUNDAMOUNT", label: "Refundamount", type: "number" },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "ACCID", label: "Accid", type: "select", ref: "account" },
      { name: "TYPE", label: "Type", type: "text" },
      { name: "COID", label: "Coid", type: "select", ref: "agent" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
      { name: "Enumber", label: "Enumber", type: "text" },
    ],
  },
  {
    key: "visaexpense", table: "VISAEXPNECE", pk: "VEXPID", label: "Visa Expenses", icon: "fa-passport",
    group: "Finance", displayField: "VEXPID",
    fields: [
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
      { name: "CATEGORYID", label: "Categoryid", type: "select", ref: "category" },
      { name: "VISACOST", label: "Visacost", type: "text" },
      { name: "OTHEREXP", label: "Otherexp", type: "text" },
      { name: "QUANTITY", label: "Quantity", type: "text" },
      { name: "NETTOTAL", label: "Nettotal", type: "text" },
    ],
  },
  {
    key: "transition", table: "TRANSITION", pk: "TID", label: "Transactions", icon: "fa-right-left",
    group: "Finance", displayField: "DESCRIPTION", agencyField: "AGENCYID",
    fields: [
      { name: "DEBIT", label: "Debit", type: "number" },
      { name: "CREDIT", label: "Credit", type: "number" },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "RECID", label: "Recid", type: "select", ref: "rec" },
      { name: "Payid", label: "Payid", type: "select", ref: "pay" },
      { name: "COID", label: "Coid", type: "select", ref: "agent" },
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
      { name: "REFUNDID", label: "Refundid", type: "select", ref: "refund" },
      { name: "ACCID", label: "Accid", type: "select", ref: "account" },
      { name: "DATE", label: "Date", type: "text" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "agentledger", table: "AGENTLEDGER", pk: "LID", label: "Agent Ledger", icon: "fa-book",
    group: "Finance", displayField: "DESCRIPTION", agencyField: "AGENCYID",
    listFilter: { field: "COID", ref: "agent" },
    fields: [
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "DATE", label: "Date", type: "date" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
      { name: "DEBIT", label: "Debit", type: "number" },
      { name: "CREDIT", label: "Credit", type: "number" },
      { name: "Enumber", label: "Enumber", type: "text" },
      { name: "recid", label: "Recid", type: "select", ref: "rec" },
      { name: "exp", label: "Exp", type: "number" },
      { name: "other", label: "Other", type: "number" },
      { name: "COID", label: "Coid", type: "select", ref: "agent" },
    ],
  },
  {
    key: "employerledger", table: "EMPLOYERLEDGER", pk: "ELID", label: "Employer Ledger", icon: "fa-book-open",
    group: "Finance", displayField: "DESCRIPTION", agencyField: "AGENCYID",
    listFilter: { field: "EMPID", ref: "employer" },
    fields: [
      { name: "DEBIT", label: "Debit", type: "number" },
      { name: "CREDIT", label: "Credit", type: "number" },
      { name: "VISANO", label: "Visano", type: "text" },
      { name: "other", label: "Other", type: "number" },
      { name: "QUANTITY", label: "Quantity", type: "number" },
      { name: "Payid", label: "Payid", type: "select", ref: "pay" },
      { name: "AGENCYID", label: "Agencyid", type: "select", ref: "company" },
      { name: "DATE", label: "Date", type: "date" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
      { name: "EMPID", label: "Empid", type: "select", ref: "employer" },
    ],
  },
  {
    key: "receivable", table: "RECEIVABLE", pk: "RID", label: "Receivables", icon: "fa-hand-holding-dollar",
    group: "Finance", displayField: "NAME",
    fields: [
      { name: "DATE", label: "Date", type: "date" },
      { name: "AMOUNT", label: "Amount", type: "number", required: true },
      { name: "RECEIVED", label: "Received", type: "number" },
      { name: "NAME", label: "Name", type: "text" },
      { name: "DESCRIPTION", label: "Description", type: "textarea" },
    ],
  },
];

// Entities shown as dashboard summary cards: [entityKey, cardLabel, isMoney, sumField]
window.DASHBOARD_CARDS = [
  ['datatable', 'DATATABLE', false, null],
  ['agent', 'Agents', false, null],
  ['company', 'Companies', false, null],
  ['employer', 'Employers', false, null],
  ['rec', 'Total Receipts', true, 'AMOUNT'],
  ['pay', 'Total Payments', true, 'PAYAMOUNT'],
];
